import AppKit
import Foundation

enum HealthReportPDFBuilder {

    static func build(from report: HealthReport) -> Data? {
        guard let canvas = PDFReportCanvas() else { return nil }

        canvas.configure(
            footer: "Generated by MacCheck",
            continuationTitle: "MacCheck · Health Report"
        )

        canvas.drawDocumentHeader(
            title: "Health Report",
            generatedAt: report.generatedAt
        )

        canvas.drawScoreBlock(
            score: report.overallScore,
            grade: HealthScoreColor.label(for: report.overallScore)
        )

        canvas.drawRule()

        canvas.drawSectionHeading("System Information")
        canvas.drawTable(rows: systemInformationRows(from: report))

        canvas.drawRule()

        canvas.drawSectionHeading("Health Categories")
        canvas.drawTable(rows: healthCategoryRows(from: report))

        canvas.drawRule()

        canvas.drawSectionHeading("Insights")
        if report.insights.isEmpty {
            canvas.drawEmptyNote("No insights recorded for this scan.")
        } else {
            canvas.drawBulletItems(
                report.insights.map { ($0.title, $0.description) }
            )
        }

        canvas.drawRule()

        canvas.drawSectionHeading("Recommendations")
        if report.recommendations.isEmpty {
            canvas.drawEmptyNote("No recommendations at this time.")
        } else {
            canvas.drawBulletItems(
                report.recommendations.map { ($0.title, $0.description) }
            )
        }

        return canvas.finalize()
    }

    // MARK: - Rows

    private static func systemInformationRows(from report: HealthReport) -> [(String, String)] {
        var rows: [(String, String)] = [
            ("Mac Model", report.systemInfo.modelName),
            ("macOS Version", report.systemInfo.macOSVersion),
            ("Model Identifier", report.systemInfo.modelIdentifier)
        ]
        if let chip = report.systemInfo.chipName, !chip.isEmpty {
            rows.insert(("Chip", chip), at: 2)
        }
        return rows
    }

    private static func healthCategoryRows(from report: HealthReport) -> [(String, String)] {
        let startupCount = report.startupApps.filter { $0.isEnabled != false }.count

        var rows: [(String, String)] = [
            ("Battery", categoryBattery(report)),
            ("Storage", "\(report.storageScore) — \(storageStatusLabel(report.storage))"),
            ("Memory", "\(report.memoryScore) — \(report.memory.status.displayName)"),
            ("Startup Apps", "\(report.startupScore) — \(startupCount) enabled")
        ]

        if let thermalScore = report.thermalScore {
            rows.append(("Thermal", "\(thermalScore) — \(report.thermal.status.displayName)"))
        } else {
            rows.append(("Thermal", report.thermal.status.displayName))
        }

        return rows
    }

    // MARK: - Helpers

    private static func categoryBattery(_ report: HealthReport) -> String {
        if let score = report.batteryScore {
            if report.battery.hasBattery, let health = report.battery.healthPercentage {
                return "\(score) — \(Int(health.rounded()))% health"
            }
            return "\(score)"
        }
        return "N/A"
    }

    private static func storageStatusLabel(_ storage: StorageInfo) -> String {
        StorageStatus.from(freePercentage: storage.freePercentage).rawValue.capitalized
    }
}
