import AppKit
import Foundation

enum InspectionReportPDFBuilder {

    static func build(from report: HealthReport) -> Data? {
        guard let canvas = PDFReportCanvas() else { return nil }

        let grade = InspectionGrade.from(healthScore: report.overallScore)

        canvas.configure(
            footer: "Generated by MacCheck",
            continuationTitle: "MacCheck · Used Mac Inspection Certificate"
        )

        canvas.drawDocumentHeader(
            title: "Used Mac Inspection Certificate",
            generatedAt: report.generatedAt
        )

        canvas.drawInspectionGrade(
            grade.rawValue,
            condition: conditionLabel(for: grade)
        )

        canvas.drawRule()

        canvas.drawSectionHeading("Device Information")
        canvas.drawDeviceLines(deviceLines(from: report))

        canvas.drawRule()

        canvas.drawSectionHeading("Inspection Summary")
        canvas.drawTable(rows: inspectionSummaryRows(from: report))

        canvas.drawRule()

        canvas.drawSectionHeading("Assessment")
        canvas.drawParagraph(assessmentText(for: grade, score: report.overallScore))

        return canvas.finalize()
    }

    // MARK: - Content

    private static func deviceLines(from report: HealthReport) -> [String] {
        var lines = [report.systemInfo.modelName]
        if let chip = report.systemInfo.chipName, !chip.isEmpty {
            lines.append(chip)
        }
        lines.append("macOS \(report.systemInfo.macOSVersion)")
        return lines
    }

    private static func inspectionSummaryRows(from report: HealthReport) -> [(String, String)] {
        [
            ("Health Score", "\(report.overallScore)"),
            ("Battery Health", batteryHealthLabel(report.battery)),
            ("Cycle Count", cycleCountLabel(report.battery)),
            ("Storage", storageSummaryLabel(report)),
            ("Memory", memorySummaryLabel(report)),
            ("Thermal", thermalSummaryLabel(report))
        ]
    }

    // MARK: - Helpers

    private static func conditionLabel(for grade: InspectionGrade) -> String {
        switch grade {
        case .a: "EXCELLENT CONDITION"
        case .b: "GOOD CONDITION"
        case .c: "FAIR CONDITION"
        case .d: "POOR CONDITION"
        }
    }

    private static func assessmentText(for grade: InspectionGrade, score: Int) -> String {
        switch grade {
        case .a:
            "This Mac is in excellent condition. Battery wear is low and no major performance concerns were detected."
        case .b:
            "This Mac is in good condition with a health score of \(score). Minor wear may be present but overall performance should remain strong."
        case .c:
            "This Mac shows fair health with a score of \(score). Review subsystem details before purchase or sale."
        case .d:
            "This Mac needs attention with a score of \(score). Inspect battery, storage, and thermal conditions carefully."
        }
    }

    private static func batteryHealthLabel(_ battery: BatteryInfo) -> String {
        guard battery.hasBattery, let health = battery.healthPercentage else { return "N/A" }
        return "\(Int(health.rounded()))%"
    }

    private static func cycleCountLabel(_ battery: BatteryInfo) -> String {
        guard battery.hasBattery else { return "N/A" }
        return "\(battery.cycleCount)"
    }

    private static func storageSummaryLabel(_ report: HealthReport) -> String {
        summaryLabel(for: report.storageScore, status: StorageStatus.from(freePercentage: report.storage.freePercentage).rawValue.capitalized)
    }

    private static func memorySummaryLabel(_ report: HealthReport) -> String {
        summaryLabel(for: report.memoryScore, status: report.memory.status.displayName)
    }

    private static func thermalSummaryLabel(_ report: HealthReport) -> String {
        if let score = report.thermalScore {
            return summaryLabel(for: score, status: report.thermal.status.displayName)
        }
        return report.thermal.status.displayName
    }

    private static func summaryLabel(for score: Int, status: String) -> String {
        switch score {
        case 85...: return "Excellent"
        case 70..<85: return "Good"
        case 55..<70: return "Fair"
        default: return status
        }
    }
}
