import AppKit
import Foundation

// MARK: - Document Style

enum PDFReportPalette {
    static let text = NSColor(calibratedRed: 0.0, green: 0.0, blue: 0.0, alpha: 1)
    static let secondary = NSColor(calibratedRed: 0.35, green: 0.35, blue: 0.37, alpha: 1)
    static let metadata = NSColor(calibratedRed: 0.50, green: 0.50, blue: 0.52, alpha: 1)
    static let rule = NSColor(calibratedRed: 0.78, green: 0.78, blue: 0.80, alpha: 1)
}

enum PDFReportMetrics {
    static let pageWidth: CGFloat = 612
    static let pageHeight: CGFloat = 792
    static let margin: CGFloat = 72
    static let footerReserved: CGFloat = 36
    static let sectionSpacing: CGFloat = 28
    static let blockSpacing: CGFloat = 14
    static let rowSpacing: CGFloat = 10
    static let tableLabelWidth: CGFloat = 200
}

enum PDFReportTypography {
    static let brand = NSFont.systemFont(ofSize: 22, weight: .semibold)
    static let documentTitle = NSFont.systemFont(ofSize: 15, weight: .regular)
    static let metadata = NSFont.systemFont(ofSize: 10, weight: .regular)
    static let sectionHeading = NSFont.systemFont(ofSize: 13, weight: .semibold)
    static let scoreLarge = NSFont.systemFont(ofSize: 36, weight: .light)
    static let gradeLarge = NSFont.systemFont(ofSize: 64, weight: .light)
    static let condition = NSFont.systemFont(ofSize: 13, weight: .semibold)
    static let body = NSFont.systemFont(ofSize: 11, weight: .regular)
    static let bodySemibold = NSFont.systemFont(ofSize: 11, weight: .semibold)
    static let tableLabel = NSFont.systemFont(ofSize: 11, weight: .regular)
    static let tableValue = NSFont.systemFont(ofSize: 11, weight: .regular)
    static let footer = NSFont.systemFont(ofSize: 9, weight: .regular)
}

// MARK: - Canvas

/// Document-style PDF renderer. Typography and spacing only — no decorative graphics.
final class PDFReportCanvas {

    private let pageWidth = PDFReportMetrics.pageWidth
    private let pageHeight = PDFReportMetrics.pageHeight
    private let margin = PDFReportMetrics.margin
    private let contentWidth: CGFloat
    private let contentBottom: CGFloat

    private var mediaBox = CGRect(x: 0, y: 0, width: 612, height: 792)
    private let data = NSMutableData()
    private let context: CGContext
    private var cursorY: CGFloat = 0
    private var pageOpen = false
    private var pageIndex = 0
    private var footerText = "Generated by MacCheck"
    private var continuationTitle = ""

    init?() {
        contentWidth = PDFReportMetrics.pageWidth - (PDFReportMetrics.margin * 2)
        contentBottom = PDFReportMetrics.pageHeight - PDFReportMetrics.margin - PDFReportMetrics.footerReserved
        guard let consumer = CGDataConsumer(data: data as CFMutableData),
              let context = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            return nil
        }
        self.context = context
        beginPage()
    }

    func configure(footer: String, continuationTitle: String) {
        footerText = footer
        self.continuationTitle = continuationTitle
    }

    func finalize() -> Data {
        if pageOpen { endPage() }
        context.closePDF()
        return data as Data
    }

    // MARK: - Document Blocks

    func drawDocumentHeader(title: String, generatedAt: Date?) {
        ensureSpace(72)
        drawText("MacCheck", font: PDFReportTypography.brand)
        cursorY += 6
        drawText(title, font: PDFReportTypography.documentTitle, color: PDFReportPalette.secondary)
        if let generatedAt {
            cursorY += 8
            drawText(
                formattedDate(generatedAt),
                font: PDFReportTypography.metadata,
                color: PDFReportPalette.metadata
            )
        }
        cursorY += PDFReportMetrics.sectionSpacing
    }

    func drawRule() {
        ensureSpace(20)
        cursorY += 6
        context.setStrokeColor(PDFReportPalette.rule.cgColor)
        context.setLineWidth(0.5)
        context.move(to: CGPoint(x: margin, y: cursorY))
        context.addLine(to: CGPoint(x: pageWidth - margin, y: cursorY))
        context.strokePath()
        cursorY += PDFReportMetrics.sectionSpacing
    }

    func drawSectionHeading(_ title: String) {
        ensureSpace(24)
        drawText(title, font: PDFReportTypography.sectionHeading)
        cursorY += PDFReportMetrics.blockSpacing
    }

    func drawScoreBlock(score: Int, grade: String) {
        ensureSpace(72)
        drawText("Overall Health Score", font: PDFReportTypography.sectionHeading)
        cursorY += 10
        drawText("\(score)", font: PDFReportTypography.scoreLarge)
        cursorY += 4
        drawText(grade, font: PDFReportTypography.body, color: PDFReportPalette.secondary)
        cursorY += PDFReportMetrics.sectionSpacing
    }

    func drawInspectionGrade(_ grade: String, condition: String) {
        ensureSpace(120)
        let gradeHeight = measuredHeight(grade, font: PDFReportTypography.gradeLarge, width: contentWidth, alignment: .center)
        drawText(grade, font: PDFReportTypography.gradeLarge, alignment: .center, fixedY: cursorY)
        cursorY += gradeHeight + 10
        drawText(condition, font: PDFReportTypography.condition, alignment: .center)
        cursorY += PDFReportMetrics.sectionSpacing
    }

    func drawTable(rows: [(label: String, value: String)]) {
        let rowHeight: CGFloat = PDFReportTypography.tableLabel.pointSize + PDFReportMetrics.rowSpacing
        ensureSpace(CGFloat(rows.count) * rowHeight)

        for row in rows {
            let y = cursorY
            drawText(
                row.label,
                font: PDFReportTypography.tableLabel,
                color: PDFReportPalette.text,
                width: PDFReportMetrics.tableLabelWidth,
                fixedY: y
            )
            drawText(
                row.value,
                font: PDFReportTypography.tableValue,
                color: PDFReportPalette.text,
                x: margin + PDFReportMetrics.tableLabelWidth,
                width: contentWidth - PDFReportMetrics.tableLabelWidth,
                fixedY: y
            )
            cursorY = y + rowHeight
        }
        cursorY += 4
    }

    func drawDeviceLines(_ lines: [String]) {
        ensureSpace(CGFloat(lines.count) * 18)
        for line in lines {
            drawText(line, font: PDFReportTypography.body)
            cursorY += 4
        }
        cursorY += 4
    }

    func drawBulletItems(_ items: [(title: String, body: String)]) {
        for item in items {
            let bodyHeight = measuredHeight(item.body, font: PDFReportTypography.body, width: contentWidth - 14)
            ensureSpace(18 + bodyHeight + 8)

            drawText("•  \(item.title)", font: PDFReportTypography.bodySemibold)
            cursorY += 2
            drawText(
                item.body,
                font: PDFReportTypography.body,
                color: PDFReportPalette.secondary,
                x: margin + 14,
                width: contentWidth - 14
            )
            cursorY += 8
        }
    }

    func drawParagraph(_ text: String) {
        let height = measuredHeight(text, font: PDFReportTypography.body, width: contentWidth)
        ensureSpace(height)
        drawText(text, font: PDFReportTypography.body, color: PDFReportPalette.secondary)
        cursorY += 4
    }

    func drawEmptyNote(_ text: String) {
        drawText(text, font: PDFReportTypography.body, color: PDFReportPalette.metadata)
        cursorY += 4
    }

    // MARK: - Primitives

    func ensureSpace(_ requiredHeight: CGFloat) {
        if cursorY + requiredHeight > contentBottom {
            endPage()
            beginPage()
        }
    }

    @discardableResult
    func drawText(
        _ text: String,
        font: NSFont,
        color: NSColor = PDFReportPalette.text,
        x: CGFloat? = nil,
        width: CGFloat? = nil,
        alignment: NSTextAlignment = .left,
        fixedY: CGFloat? = nil
    ) -> CGFloat {
        let drawX = x ?? margin
        let drawWidth = width ?? contentWidth
        let resolvedColor = color.usingColorSpace(.deviceRGB) ?? PDFReportPalette.text

        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = alignment
        paragraph.lineBreakMode = .byWordWrapping

        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: resolvedColor,
            .paragraphStyle: paragraph
        ]

        let height = measuredHeight(text, font: font, width: drawWidth, alignment: alignment)
        let drawY = fixedY ?? cursorY

        if fixedY == nil { ensureSpace(height) }

        let rect = CGRect(x: drawX, y: drawY, width: drawWidth, height: height)
        let attributed = NSAttributedString(string: text, attributes: attributes)

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(cgContext: context, flipped: true)
        attributed.draw(with: rect, options: [.usesLineFragmentOrigin, .usesFontLeading])
        NSGraphicsContext.restoreGraphicsState()

        if fixedY == nil {
            cursorY = drawY + height
        } else {
            cursorY = max(cursorY, drawY + height)
        }

        return height
    }

    // MARK: - Private

    private func beginPage() {
        if pageOpen { endPage() }

        pageIndex += 1
        var pageMediaBox = mediaBox
        context.beginPage(mediaBox: &pageMediaBox)

        context.saveGState()
        context.translateBy(x: 0, y: pageHeight)
        context.scaleBy(x: 1, y: -1)

        cursorY = margin
        pageOpen = true

        if pageIndex > 1, !continuationTitle.isEmpty {
            drawText(continuationTitle, font: PDFReportTypography.metadata, color: PDFReportPalette.metadata)
            cursorY += 16
        }
    }

    private func endPage() {
        guard pageOpen else { return }

        let footerY = pageHeight - margin
        drawText(
            footerText,
            font: PDFReportTypography.footer,
            color: PDFReportPalette.metadata,
            fixedY: footerY
        )

        if pageIndex > 1 {
            drawText(
                "Page \(pageIndex)",
                font: PDFReportTypography.footer,
                color: PDFReportPalette.metadata,
                alignment: .right,
                fixedY: footerY
            )
        }

        context.restoreGState()
        context.endPDFPage()
        pageOpen = false
    }

    private func measuredHeight(
        _ text: String,
        font: NSFont,
        width: CGFloat,
        alignment: NSTextAlignment = .left
    ) -> CGFloat {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = alignment
        paragraph.lineBreakMode = .byWordWrapping
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .paragraphStyle: paragraph
        ]
        let attributed = NSAttributedString(string: text, attributes: attributes)
        let bounding = attributed.boundingRect(
            with: CGSize(width: width, height: .greatestFiniteMagnitude),
            options: [.usesLineFragmentOrigin, .usesFontLeading]
        )
        return max(ceil(bounding.height), font.pointSize * 1.2)
    }

    private func formattedDate(_ date: Date) -> String {
        date.formatted(date: .long, time: .shortened)
    }
}
